### ISSUE TITLE
please release latest changes in new version of gem

### ISSUE THREAD

**Issue by dmitry-a-l** [6twenty/modest_model#1]

**Comment by 6twenty** [comment]
Apologies for the delay in releasing the newer version. There are still some issues to be ironed out before the release and unfortunately not much time to dedicate to the project, but we're working on it :)

**Comment by dmitry-a-l** [comment]
Hm, I run tests without any failure :)

**Comment by 6twenty** [comment]
The test suite is fine; some of the additional functionality lacks coverage in areas which we'd like to support for the next release, but which we've encountered some issues when implementing. Please bear with us :)

**Comment by 6twenty** [comment]
Well it's been several years and it still looks like I won't be getting around to any of those changes anytime soon. Gonna close this one.
